#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# Delivery service identity
###################################################################################################
{{- $fullname := include "delivery.fullname" . | replace "." "" }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: List
items:
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentity
    metadata:
      name: {{ $fullname }}-identity
      namespace: {{ $fullname }}-namespace
    spec:
      type: 0
      clientID: {{ .Values.identity.clientid }}
      resourceID: {{ .Values.identity.resourceid }}
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentityBinding
    metadata:
      name: {{ $fullname }}-identity-binding
      namespace: {{ $fullname }}-namespace
    spec:
      azureIdentity: {{ $fullname }}-identity
      selector: {{ $fullname }}
