apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-v0.1.0-dev
  namespace: backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: fabrikam-delivery
        image: kammana/nodeapp:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "350Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"
        env:
        - name: IDENTITY_CLIENT_ID
          value: "b119ba51-bed8-41d5-b431-352ae1d939e5"
        - name: IDENTITY_RESOURCE_ID
          value: "/subscriptions/6c7fe35c-5b46-4d5d-8309-d406d9bf864b/resourceGroups/rg-shipping-dronedelivery/providers/Microsoft.ManagedIdentity/userAssignedIdentities/dev-d"
        - name: COSMOSDB_ID
          value: "d-utmp26hh455de"
        - name: COSMOSDB_COLLECTION_ID
          value: "d-utmp26hh455de-col"
        - name: REASON
          value: "Initial deployment"
        - name: ENVS_DEV
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: backend-dev
spec:
  selector:
    app: delivery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: backend-dev
spec:
  podSelector:
    matchLabels:
      app: delivery
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: "10.240.0.0/22"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress
  namespace: backend-dev
spec:
  podSelector:
    matchLabels:
      app: delivery
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: "10.240.4.16/28"
