#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

kind: Namespace
apiVersion: v1
metadata:
  name: backend-dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev
  namespace: backend-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 10Gi
    pods: "10"
